/*==============================================================*/
/* CONSULTA 1                       					*/
/*  - Mostrar histórico de rendimiento por programas. En una columna
debe aparecer el año lectivo, en otra columna el nombre del programa, 
en otra columna la cantidad de rendimientos buenos, en otra columna 
la cantidad de rendimientos excelentes, en otra columna la cantidad
de rendimientos regulares. */
/*==============================================================*/
SELECT T1.ANO, T4.NOMBRE_PROGRAMA, T1.BUENOS, T2.REGULARES, T3.EXCELENTES
FROM
(SELECT ANO, COUNT(NOMBRE_RENDIMIENT) AS BUENOS FROM RENDIMIENTO REN
INNER JOIN TIPO_RENDIMIENTO TIPO ON TIPO.ID_TIPO_RENDIMIENT = REN.ID_TIPO_RENDIMIENT
INNER JOIN ACTIVIDAD ACT ON ACT.ID_ACTIVIDAD = REN.ID_ACTIVIDAD
INNER JOIN PROGRAMA PRO ON PRO.ID_PROGRAMA = ACT.ID_PROGRAMA
INNER JOIN CREADO CRD ON CRD.ID_ACTIVIDAD = ACT.ID_ACTIVIDAD
INNER JOIN ANO_LECTIVO LECT ON LECT.ID_ANO_LECTIVO = CRD.ID_ANO_LECTIVO
WHERE NOMBRE_RENDIMIENT LIKE 'BUE%'
GROUP BY LECT.ID_ANO_LECTIVO) T1
INNER JOIN 
(SELECT ANO, COUNT(NOMBRE_RENDIMIENT) AS REGULARES FROM RENDIMIENTO REN
INNER JOIN TIPO_RENDIMIENTO TIPO ON TIPO.ID_TIPO_RENDIMIENT = REN.ID_TIPO_RENDIMIENT
INNER JOIN ACTIVIDAD ACT ON ACT.ID_ACTIVIDAD = REN.ID_ACTIVIDAD
INNER JOIN PROGRAMA PRO ON PRO.ID_PROGRAMA = ACT.ID_PROGRAMA
INNER JOIN CREADO CRD ON CRD.ID_ACTIVIDAD = ACT.ID_ACTIVIDAD
INNER JOIN ANO_LECTIVO LECT ON LECT.ID_ANO_LECTIVO = CRD.ID_ANO_LECTIVO
WHERE NOMBRE_RENDIMIENT LIKE 'REG%'
GROUP BY LECT.ID_ANO_LECTIVO) T2
ON T1.ANO = T2.ANO
INNER JOIN
(SELECT ANO, COUNT(NOMBRE_RENDIMIENT) AS EXCELENTES FROM RENDIMIENTO REN
INNER JOIN TIPO_RENDIMIENTO TIPO ON TIPO.ID_TIPO_RENDIMIENT = REN.ID_TIPO_RENDIMIENT
INNER JOIN ACTIVIDAD ACT ON ACT.ID_ACTIVIDAD = REN.ID_ACTIVIDAD
INNER JOIN PROGRAMA PRO ON PRO.ID_PROGRAMA = ACT.ID_PROGRAMA
INNER JOIN CREADO CRD ON CRD.ID_ACTIVIDAD = ACT.ID_ACTIVIDAD
INNER JOIN ANO_LECTIVO LECT ON LECT.ID_ANO_LECTIVO = CRD.ID_ANO_LECTIVO
WHERE NOMBRE_RENDIMIENT LIKE 'EXC%'
GROUP BY LECT.ID_ANO_LECTIVO) T3
ON T1.ANO = T3.ANO
INNER JOIN
(
SELECT ANO, NOMBRE_PROGRAMA FROM RENDIMIENTO REN
INNER JOIN TIPO_RENDIMIENTO TIPO ON TIPO.ID_TIPO_RENDIMIENT = REN.ID_TIPO_RENDIMIENT
INNER JOIN ACTIVIDAD ACT ON ACT.ID_ACTIVIDAD = REN.ID_ACTIVIDAD
INNER JOIN PROGRAMA PRO ON PRO.ID_PROGRAMA = ACT.ID_PROGRAMA
INNER JOIN CREADO CRD ON CRD.ID_ACTIVIDAD = ACT.ID_ACTIVIDAD
INNER JOIN ANO_LECTIVO LECT ON LECT.ID_ANO_LECTIVO = CRD.ID_ANO_LECTIVO
GROUP BY ANO, NOMBRE_PROGRAMA) T4
ON T1.ANO = T4.ANO
ORDER BY ANO ASC;