/*==============================================================*/
/* CONSULTA 2                       					*/
/*  -Mostrar histórico de cantidad de profesores por período. En una 
columna aparecerá el año lectivo, en otra columna aparecerá el número 
de mujeres, en otra columna aparecerá el número de hombres.  */
/*==============================================================*/
SELECT T1.ANO, T1.MASCULINOS, T2.FEMENINOS
FROM
(SELECT LECT.ID_ANO_LECTIVO, ANO, COUNT(PRF.ID_PROF) AS MASCULINOS  FROM PROFESIONAL PRF
INNER JOIN GENERO GEN ON GEN.ID_GENERO = PRF.ID_GENERO
INNER JOIN ACTIVIDAD ACT ON ACT.ID_ACTIVIDAD = PRF.ID_ACTIVIDAD
INNER JOIN CREADO CRD ON CRD.ID_ACTIVIDAD = ACT.ID_ACTIVIDAD
INNER JOIN ANO_LECTIVO LECT ON LECT.ID_ANO_LECTIVO = CRD.ID_ANO_LECTIVO
WHERE NOMBRE_GENERO LIKE 'Mas%'
GROUP BY LECT.ID_ANO_LECTIVO) T1
INNER JOIN
(SELECT LECT.ID_ANO_LECTIVO, COUNT(PRF.ID_PROF) AS FEMENINOS  FROM PROFESIONAL PRF
INNER JOIN GENERO GEN ON GEN.ID_GENERO = PRF.ID_GENERO
INNER JOIN ACTIVIDAD ACT ON ACT.ID_ACTIVIDAD = PRF.ID_ACTIVIDAD
INNER JOIN CREADO CRD ON CRD.ID_ACTIVIDAD = ACT.ID_ACTIVIDAD
INNER JOIN ANO_LECTIVO LECT ON LECT.ID_ANO_LECTIVO = CRD.ID_ANO_LECTIVO
WHERE NOMBRE_GENERO LIKE 'Fem%'
GROUP BY LECT.ID_ANO_LECTIVO) T2
ON T1.ID_ANO_LECTIVO = T2.ID_ANO_LECTIVO
ORDER BY T1.ANO ASC;