/*
CONSULTA 3
– Mostrar histórico de matriculaciones y deserciones. 
En una columna deberá aparecer el año lectivo, en otra 
columna el número de matriculados, en otra columna el 
número de retirados. 
*/
SELECT T1.ANO, T1.MATRICULADOS, T2.RETIRADOS
FROM
(SELECT ANO, COUNT(ID_MATRICULA) AS MATRICULADOS FROM MATRICULA MAT
INNER JOIN ACTIVIDAD ACT ON ACT.ID_ACTIVIDAD = MAT.ID_ACTIVIDAD
INNER JOIN CREADO CRD ON CRD.ID_ACTIVIDAD = ACT.ID_ACTIVIDAD
INNER JOIN ANO_LECTIVO LECT ON LECT.ID_ANO_LECTIVO = CRD.ID_ANO_LECTIVO
WHERE ESTADO_MATRICULA = TRUE 
GROUP BY ANO) T1
INNER JOIN 
(SELECT  ANO, COUNT(ID_MATRICULA) AS RETIRADOS FROM MATRICULA MAT
INNER JOIN ACTIVIDAD ACT ON ACT.ID_ACTIVIDAD = MAT.ID_ACTIVIDAD
INNER JOIN CREADO CRD ON CRD.ID_ACTIVIDAD = ACT.ID_ACTIVIDAD
INNER JOIN ANO_LECTIVO LECT ON LECT.ID_ANO_LECTIVO = CRD.ID_ANO_LECTIVO
WHERE ESTADO_MATRICULA = FALSE 
GROUP BY ANO) T2
ON T1.ANO = T2.ANO
ORDER BY T1.ANO ASC;