/*
CONSULTA 4
- Mostrar total de valores recaudados por cada año lectivo. 
*/
SELECT ANO, SUM(PRECIO_MATRICULA) FROM MATRICULA MAT
INNER JOIN ACTIVIDAD ACT ON ACT.ID_ACTIVIDAD = MAT.ID_ACTIVIDAD
INNER JOIN CREADO CRD ON CRD.ID_ACTIVIDAD = ACT.ID_ACTIVIDAD
INNER JOIN ANO_LECTIVO LECT ON LECT.ID_ANO_LECTIVO = CRD.ID_ANO_LECTIVO
GROUP BY ANO
ORDER BY ANO ASC;