/*
CURSOR
-Cursor que muestre la cantidad de niños y niñas inscritas en cada año lectivo del ciclo. 
*/
DO $$
DECLARE
    NINOS INT := 0;
    NINAS INT := 0;
    --Creación del cursor explicito
    C_NINOS CURSOR FOR SELECT ANO, NI.ID_NINIO, NOMBRE_GENERO FROM ACTIVIDAD ACT
    INNER JOIN MATRICULA MAT ON ACT.ID_ACTIVIDAD = MAT.ID_ACTIVIDAD
    INNER JOIN NINIO NI ON NI.ID_NINIO = MAT.ID_NINIO
    INNER JOIN GENERO GEN ON GEN.ID_GENERO = NI.ID_GENERO
    INNER JOIN CREADO CRD ON CRD.ID_ACTIVIDAD = ACT.ID_ACTIVIDAD
    INNER JOIN ANO_LECTIVO LECT ON LECT.ID_ANO_LECTIVO = CRD.ID_ANO_LECTIVO
    GROUP BY ANO, NI.ID_NINIO, NOMBRE_GENERO;

    C_PERIODO CURSOR FOR SELECT * FROM ANO_LECTIVO LECT;

BEGIN
 FOR ANIO IN C_PERIODO
  LOOP
      NINOS = 0;
    NINAS = 0;
    FOR NINO IN C_NINOS 
        LOOP
            NINOS = NINOS + COUNT(NINO.ID_NINIO) WHERE NINO.NOMBRE_GENERO LIKE 'Mas%' AND ANIO.ANO = NINO.ANO;
            NINAS = NINAS + COUNT(NINO.ID_NINIO) WHERE NINO.NOMBRE_GENERO LIKE 'Fem%' AND ANIO.ANO = NINO.ANO;
    END LOOP;
        RAISE NOTICE 'PERIODO LECTIVO:%        NIÑOS:%     NIÑAS:%', ANIO.ANO, NINOS, NINAS;
  END LOOP;
END; 
$$ LANGUAGE 'plpgsql';