SELECT ANO, COUNT(ACT.ID_ACTIVIDAD) FROM ACTIVIDAD ACT
    INNER JOIN PROGRAMA PRG ON PRG.ID_PROGRAMA = ACT.ID_PROGRAMA
    INNER JOIN CREADO CRD ON CRD.ID_ACTIVIDAD = ACT.ID_ACTIVIDAD
    INNER JOIN ANO_LECTIVO LECT ON LECT.ID_ANO_LECTIVO = CRD.ID_ANO_LECTIVO
    GROUP BY ANO
	ORDER BY ANO ASC;