CREATE OR REPLACE FUNCTION TG_IMPIDE_MATRICULA() RETURNS TRIGGER
AS
$$
    DECLARE
        MAX_MAT INT := 1;
        NUM INT;

    BEGIN
        --YA AHORA SI ESO
        SELECT COUNT(ID_MATRICULA) INTO NUM FROM MATRICULA 
        WHERE ID_NINIO = NEW.ID_NINIO AND ID_ACTIVIDAD = NEW.ID_ACTIVIDAD;

        IF(NUM>=MAX_MAT) THEN
            RAISE EXCEPTION 'SOLO SE PUEDE MATRICULAR UNA VEZ';
        END IF;
        RETURN NEW;
    END;
    $$
    LANGUAGE PLPGSQL;

--creación del trigger
CREATE TRIGGER TG_IMPIDE_MATRICULA
BEFORE
INSERT ON MATRICULA
FOR EACH ROW
EXECUTE PROCEDURE TG_IMPIDE_MATRICULA();
--DATO DE PRUEBA
--ESTOY INTENTANDO INGRESAR UN NIÑO QUE YA FUÉ INSCRITO A ESA ACTIVIDAD:
/*
INSERT INTO MATRICULA (ID_ACTIVIDAD,ID_NINIO,ESTADO_MATRICULA,PRECIO_MATRICULA) VALUES
												(1,1,TRUE,10);*/